ur5e:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  ur5e_arm_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    constraints:
      goal_time: 2.0
      stopped_velocity_tolerance: 0.05
      goal_tolerance: 0.05


  ur5e_gripper_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - gripper_robotiq_hande_joint_finger
    constraints:
      goal_time: 2.0
      stopped_velocity_tolerance: 0.05
      goal_tolerance: 0.01
    gains:
      gripper_robotiq_hande_joint_finger: {p: 100.0, i: 0.01, d: 1.0}
