ur5e_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
  gains:
    shoulder_pan_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder_lift_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbow_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
ur5e_gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - gripper_robotiq_hande_joint_finger
  gains:
    gripper_robotiq_hande_joint_finger:
      p: 100
      d: 1
      i: 1
      i_clamp: 1 

controller_list:
  - name: ur5e/ur5e_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: ur5e/ur5e_gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - gripper_robotiq_hande_joint_finger